### ISSUE TITLE
kiwi browser for android 

### ISSUE THREAD

**Issue by deaddogwalking** [Nystik-gh/Novel-AI-Enhancements#3]
hello!! i just wanted to say that i got this working for kiwi browser on android using violentmonkey specifically. i couldnt get it to work properly with tampermonkey. i had a little trouble with chunk errors when trying to load stories at first, but i have ublock origin installed, and disabling it for the novel ai site seemed to solve that.

**Comment by deaddogwalking** [comment]
okay, spoke a little bit too soon. the subshelves do initialize, but trying to create one just leads to endless loading

**Comment by Nystik-gh** [comment]
Hello! Thanks for reporting.

Yeah I just had a look myself, interesting that Tampermonkey doesn't even load the script.

And like you said there seems to be some issue with the various shelf actions in Violentmonkey. My account which has subshelves,  I'm unable to navigate inside them and also the breadcrumbs aren't clickable.

If I find some extra time I'll try to debug this, but I can't make any promises of supporting a ton of different browsers,

**Comment by deaddogwalking** [comment]
of course, youre welcome!! i just figured i would give it a try and report back, since kiwi supports add-ons and i know a decent number of people use it. but i appreciate you looking into it, even if you dont end up able to debug it :]!!

**Comment by Nystik-gh** [comment]
Looks like I did get some spare time today. Do you mind testing this version and see if it works for you?

[hotfix 1.0.5](https://github.com/Nystik-gh/Novel-AI-Enhancements/raw/03-kiwi-browser-violentmonkey/subshelves/dist/naie-subshelves.user.js)

**Comment by Nystik-gh** [comment]
As for Tampermonkey, this seems to be a known issue, see [here](https://github.com/Tampermonkey/tampermonkey/issues/2055#issuecomment-2225237330)

**Comment by deaddogwalking** [comment]
it does work!! im able to create sub-shelves, move things into them, rename, delete, etc.!! hopefully that kiwi bug gets fixed eventually, thanks for letting me know about it. if i do run into anything weird with the script and the browser again, ill let you know, but its working as intended now!

**Comment by Nystik-gh** [comment]
I'm merging this into the main code, so if you wanna be able to update the script easily in the future you probably wanna install it from this link again: [main release](https://github.com/Nystik-gh/Novel-AI-Enhancements/raw/main/subshelves/dist/naie-subshelves.user.js)
